#!/bin/sh

## clear the logs (quietly)
rm -f intermine.log

## echo a big marker so we can see when this run started in the scroll
echo "##################################################################################################"
echo "###################################### integrate #################################################"
echo "##################################################################################################"

## ontologies
# ./gradlew integrate -Psource=go
# ./gradlew integrate -Psource=so
# ./gradlew integrate -Psource=to
# ./gradlew integrate -Psource=po

## LIS chado
#./gradlew integrate -Psource=lis-genomics
#./gradlew integrate -Psource=lis-genetics
#./gradlew integrate -Psource=lis-featureprop
#./gradlew integrate -Psource=lis-genefamilies
#./gradlew integrate -Psource=lis-reactome-file

## PeanutBase chado
#./gradlew integrate -Psource=peanutbase-genetics --stacktrace
#./gradlew integrate -Psource=peanutbase-featureprop --stacktrace

## ---------------------------------------------------------------------------------------------------------
## - ALL of the chado loaders must be DONE before continuing, because identifiers are changed by SQL below -
## ---------------------------------------------------------------------------------------------------------

./gradlew generateUpdateTriggers
psql peanutmine-dev -f dbmodel/build/resources/main/add-update-triggers.sql
psql peanutmine-dev -f ../legfed-intermine-sql/update-organism-genus-species.sql
psql peanutmine-dev -f ../legfed-intermine-sql/update-organism-descriptions.sql
psql peanutmine-dev -f ../legfed-intermine-sql/update-strain-descriptions.sql
psql peanutmine-dev -f ../legfed-intermine-sql/update-identifiers.sql
psql peanutmine-dev -f dbmodel/build/resources/main/remove-update-triggers.sql

## files
./gradlew integrate -Psource=peanut-geneticmarker-gff
./gradlew integrate -Psource=peanut-synteny-gff
./gradlew integrate -Psource=peanut-expression
