#!/bin/sh
rm -f intermine.log

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "#################################################### PEANUTMINE INTEGRATE ################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies and InterPro
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=go --stacktrace

./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace

./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace

## about
./gradlew integrate -Psource=aradu-about --stacktrace
./gradlew integrate -Psource=araip-about --stacktrace
./gradlew integrate -Psource=arahy-about --stacktrace

## chromosome-fasta
./gradlew integrate -Psource=aradu.V14167.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2-chromosome-fasta --stacktrace

## cds-fasta
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2.ann1-cds-fasta --stacktrace

## protein-fasta
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2.ann1-protein-fasta --stacktrace

## mrna-fasta
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2.ann1-mrna-fasta --stacktrace

## gff
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2.ann1-gff --stacktrace

## gfa
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1-gfa --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1-gfa --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.ann1-gfa --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2.ann1-gfa --stacktrace

## pathway
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1-pathway --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1-pathway --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.ann1-pathway --stacktrace
./gradlew integrate -Psource=arahy.Tifrunner.gnm2.ann1-pathway --stacktrace

## synteny
./gradlew integrate -Psource=aradu.V14167.gnm1.ann1.syn1-synteny --stacktrace
./gradlew integrate -Psource=araip.K30076.gnm1.ann1.syn1-synteny --stacktrace

## mrk-gff
./gradlew integrate -Psource=arahy.Tifrunner.gnm1.mrk-gff --stacktrace

## mixed-gwas
./gradlew integrate -Psource=arahy.mixed-gwas --stacktrace
