#!/bin/sh
echo "********** peanutmine/integrate **********"
ant clean

# ontologies
#pg_restore -d peanutmine /home/analysis/shokin/dumps/peanutmine.ontologies.dat
#ant -v -Dsource=go,so,to,po
#pg_dump -Fc peanutmine > /home/analysis/shokin/dumps/peanutmine.ontologies.dat

# chado
#pg_restore -d peanutmine /home/analysis/shokin/dumps/peanutmine.chado.dat
ant -v -Dsource=lis-genomics,peanutbase-genetics,lis-featureprop,lis-genefamilies,lis-homology,lis-go,lis-reactome-file
#pg_dump -Fc peanutmine > /home/analysis/shokin/dumps/peanutmine.chado.dat

# update organisms and identifiers


# non-chado
#ant -v -Dsource=gff-geneticmarkers,file-synteny,peanut-expression
