#!/bin/sh
echo "********** peanutmine/integrate **********"
ant clean
#ant -Dsource=go
#ant -Dsource=so
ant -Dsource=chado-genomics
ant -Dsource=chado-genetics
ant -Dsource=chado-featureprop
ant -Dsource=chado-go
ant -Dsource=chado-reactome-file
ant -Dsource=gff-geneticmarkers
ant -Dsource=file-synteny
ant -Dsource=entrez-organism
